runtime: python

env: flex
entrypoint: gunicorn -b :$PORT main:app

beta_settings:
  cloud_sql_instances:

runtime_config:
  python_version: 3.7

env_variables:
  CLOUD_SQL_CONNECTION_NAME:
  DB_USER:
  DB_PASS:
  DB_NAME:
