runtime: python

env: flex
entrypoint: gunicorn -b :$PORT main:app

beta_settings:
  cloud_sql_instances: 

runtime_config:
  python_version: 3.7

automatic_scaling:
  max_num_instances: 8

resource:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  CLOUD_SQL_CONNECTION_NAME: 
  DB_USER: 
  DB_PASS: 
  DB_NAME: 
  EMAIL_USER: 
  EMAIL_PASSWORD:
  STRIPE_PUBLISHABLE_KEY: 
  STRIPE_SECRET_KEY: 

